{
 "title": "Drupal",
 "description": "Dashboard monitoring key statistics for Drupal 8",
 "tags": [
  "prometheus",
  "php-fpm",
  "drupal"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "PHP-FPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Listen Queue Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_listen_queue_connections{kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "Queued Connections"
    },
    {}
   ]
  },
  {
   "title": "Active Processes (% of total)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_processes_total{state=\"active\",kubernetes_namespace=~\"$namespace\"})/sum(phpfpm_processes_total{kubernetes_namespace=~\"$namespace\"}) * 100",
     "legendFormat": "active processes"
    }
   ]
  },
  {
   "title": "Memory Usage (% of requested)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"php-fpm\",namespace=~\"$namespace\"}) / sum(kube_pod_container_resource_requests_memory_bytes{container=\"php-fpm\",namespace=~\"$namespace\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Usage (% of requested)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"php-fpm\",namespace=~\"$namespace\"}[2m])) / sum(kube_pod_container_resource_requests_cpu_cores{container=\"php-fpm\",namespace=~\"$namespace\"}) * 100",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "PHP-FPM Processes",
   "type": "graph",
   "description": "Total processes php is using",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "sum(phpfpm_processes_total{state=\"active\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(phpfpm_processes_total{state=\"idle\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(phpfpm_processes_total{kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(phpfpm_processes_total{kubernetes_namespace=~\"$namespace\"})/15",
     "legendFormat": "pods"
    }
   ]
  },
  { "title": "Varnish", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Hitrate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(varnish_main_cache_hit{kubernetes_namespace=~\"$namespace\"}) / (sum(varnish_main_cache_miss{kubernetes_namespace=~\"$namespace\"}) + sum(varnish_main_cache_hit{kubernetes_namespace=~\"$namespace\"})) * 100"
    }
   ]
  },
  {
   "title": "Varnish Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(varnish_main_n_lru_nuked{kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "nuked"
    },
    {
     "expr": "sum(rate(varnish_main_backend_fail{kubernetes_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "backend failures"
    },
    {
     "expr": "sum(varnish_main_sessions{type=\"dropped\",kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "dropped sessions"
    }
   ]
  },
  {
   "title": "Varnish Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{kubernetes_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Client Requests"
    },
    {
     "expr": "sum(irate(varnish_backend_req{kubernetes_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Backend Requests"
    }
   ]
  },
  {
   "title": "Varnish Memory Usage (% of requested)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name=\"varnish\",namespace=~\"$namespace\"}) / sum(kube_pod_container_resource_requests_memory_bytes{container=\"varnish\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Varnish CPU Usage (% of requested)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"varnish\",namespace=~\"$namespace\"}[2m])) / sum(kube_pod_container_resource_requests_cpu_cores{container=\"varnish\",namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Hitrate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{kubernetes_namespace=~\"$namespace\"}[5m])) / (sum(irate(redis_keyspace_hits_total{kubernetes_namespace=~\"$namespace\"}[5m])) + sum(irate(redis_keyspace_misses_total{kubernetes_namespace=~\"$namespace\"}[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Hits/Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_keyspace_hits_total{kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(irate(redis_keyspace_misses_total{kubernetes_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}